version: '3'
services:
  app:
    depends_on: [ 'db-migrate' ]
    build:
       context: .
       dockerfile: Dockerfile
    ports:
     - 8080:3000
    networks:
     - internal
    environment:
      DATABASE_URL: mysql://home:home@db/home
      SECRET_KEY: totallysecretkey
      EXPIRES_SECONDS: 3600
      MASTER_PASSWORD: admin  # username: admin

  db-migrate:
    depends_on: [ 'db' ]
    build:
       context: .
       dockerfile: Dockerfile
    networks:
      - internal
    environment:
      DATABASE_URL: mysql://home:home@db/home
    command: [ "npm", "run", "db-migrate" ]

  db:
    image: mysql:latest
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3333:3306
    networks:
      - internal
    environment:
      MYSQL_USER: home
      MYSQL_PASSWORD: home
      MYSQL_DATABASE: home
      MYSQL_ROOT_PASSWORD: root
  
  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  database: